apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: gustavobi4yourdata
  GITSYNC_USERNAME: gustavobi4yourdata
  GIT_SYNC_PASSWORD: Z2hwX2xRTkt0UldpUVJ1aUhxUWVnZzVDM2Y3VGkzYnljQjA3cWd6Yw==
  GITSYNC_PASSWORD: Z2hwX2xRTkt0UldpUVJ1aUhxUWVnZzVDM2Y3VGkzYnljQjA3cWd6Yw==

