apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: Z3VzdGF2b3NvdXphX3VuaWZlaUB5YWhvby5jb20uYnI=
  GITSYNC_USERNAME: Z3VzdGF2b3NvdXphX3VuaWZlaUB5YWhvby5jb20uYnI=
  GIT_SYNC_PASSWORD: Z2l0aHViX3BhdF8xMUE1NUxNTEkwZGRkYzlncWRXTGtfOXNVU0lmSTBTKjhlak9tWTNybXJwUTB6a3RoWkVSeFlFWXpRRVdNb2FZVENON0xUMjRMYndhNEVZd1o=
  GITSYNC_PASSWORD: Z2l0aHViX3BhdF8xMUE1NUxNTEkwZGRkYzlncWRXTGtfOXNVU0lmSTBTKjhlak9tWTNybXJwUTB6a3RoWkVSeFlFWXpRRVdNb2FZVENON0xUMjRMYndhNEVZd1o=
