apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gustavobi4yourdata/cluster-k8s.git'
    path: infra/src/helm-charts/minio-tenant
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: 'docker-desktop'
      namespace: deepstorage
      server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
