apiVersion: v1
kind: Secret
metadata:
  name: private-key
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData: 
  url: https://github.com/gustavobi4yourdata/cluster-k8s.git
  password: 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
  username: not-used


  